config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: "pages#about"
  get '/hashtags', to: "pages#hashtags"

  get 'users/:id/posts' => 'users#posts', :as => :user_posts

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  validates :tag_list, presence: true

  has_many :comments, dependent: :destroy
  belongs_to :user

  acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name

  has_many :posts, dependent: :destroy # || comment this in if we want to delete a user's posts if the user cancels their account (but some websites just keep them around and replace the username with "deleted")
  has_many :comments, dependent: :destroy # || nearly identical logic as the comment in line 7
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      redirect_to @post
    else
      # flash.now[:errors] = @comment.errors.full_messages || this shows the alert message like ["body can't be blank"]
      render :new # the new.html.erb has a partial that has more descriptive (though not aesthetic) errors
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:success] = "Comment successfully deleted."
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def hashtags
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = if params[:term]
      Post.where('title ILIKE?', "%#{params[:term]}%").order('id DESC')
    elsif params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.order('created_at DESC').page(params[:page]).per(3)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Post successfully created."
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id && @post.update(post_params)
      flash[:success] = "Post successfully updated."
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post successfully deleted."

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :term, :tag_list)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def posts
    @user = User.find(params[:id])
    @posts = @user.posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.user.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>

<% if user_signed_in? && current_user.id == comment.user_id %>
  <p><%= link_to 'Delete', [comment.post, comment],
                        method: :delete,
                        class: "button",
                        data: { confirm: "Are you sure?" } %>
  </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.create]) do |f| %>
    <%= f.text_area :body, placeholder: "Please put your comment here..." %>
  </p>

  <br>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/new.html.erb
<div id="page_wrapper">
<h1>New Comment</h1><br>
  <%= render 'shared/errors' %><br>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggah</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/assets/ubecon.jpg" rel="shortcut icon" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <%= favicon_link_tag 'ubecon.jpg' %> -->
  </head>
  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "ubecon.jpg" %>
        <% end %>
      </div>

      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Posts", user_posts_path(current_user) %></li>
        <% end %>
        <li><%= link_to "Topics", hashtags_path %></li>
        <li> <%= link_to "About", about_path %></li>
      </ul>

      <ul>
        <li class="category">Blogging Websites</li>
        <li><a href="http://www.tumblr.com">Tumblr</a></li>
        <li><a href="http://www.xanga.com">Xanga</a></li>
        <li><a href="http://www.blogger.com">Blogger</a></li>
        <li><a href="http://www.wordpress.com">Wordpress</a></li>
        <li><a href="http://www.medium.com">Medium</a></li>
      </ul>
    </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) && user_signed_in? %>
          <p>Welcome, <%= current_user.name %>!</p>
          <% elsif current_page?(about_path) %>
          <p>About</p>
          <% elsif current_page?(root_path) && !user_signed_in? %>
          <p>All Posts</p>
          <% else %>
          <%= link_to root_path do %>
            <i style="font-size:16px" class="fa">&#xf177;</i> Back to All Posts
          <% end %>
      <% end %>

    <% if user_signed_in? %>
      <div class="buttons">
        <button class="button"><%= link_to "New Post", new_post_path %></button>
        <button class="button"><%= link_to 'Account', edit_user_registration_path %></button>
        <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
      </div>
    <% end %>

    <% if !user_signed_in? %>
    <div class="buttons">
      <button class="button"><%= link_to "Sign Up", new_user_registration_path %></button>
    </div>
    <% end %>

    <% if !user_signed_in? %>
    <div class="buttons">
    <form action="<%= new_user_session_path %>" method="POST">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
    <p>Email <input class="facebook" type="text" name="user[email]" required></p>
    <p>Password <input class="facebook" type="password" name="user[password]" required></p>
        <button class="button">Log In</button>
    </form>
  </div>
    <% end %>

    <% if user_signed_in? %>
    <div class="buttons">
      <form action="<%= posts_path %>" method="GET">
        <input class="search-bar" type="text" name="<%= :term %>" value="<%= params[:term] %>" placeholder="Search">
      </form>
    </div>
    <% end %>

  </div>


  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
			<header class="the-header-part">
				<h1>Allan James Lapid <span>Brooklyn, New York</span></h1>
			</header>

			<div class="grid">
				<figure class="cool-effect">
					<figcaption>
						<h2>ALLAN <span>JAMES</span> Lapid</h2>
						<p>^.^ Hello, it me ^.^</p>
					</figcaption>
				</figure>
			</div>

		</div>

app/views/pages/hashtags.html.erb
<div class="container">
			<header class="the-header-part">
				<h1>Tagged Topics</h1>
			</header>

  <div class="grid">

    <div id="tag_cloud">
      <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
      #<%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div>

  </div>

</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :tag_list, "Tags (separated by commas)" %><br>
    <%= f.text_field :tag_list %>
  </p>


  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>Edit Post</h1>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date">
      Author: <%= link_to post.user.name, user_posts_path(post.user), :style=>'color: #4d94ff;' %><br>
      Date: <%= post.created_at.strftime("%B, %d, %Y") %><br>
      Tags: <%= raw post.tag_list.map { |t| link_to t.capitalize, tag_path(t),:style=>'color: #4d94ff;' }.join(", ") %>
    </p>
  </div>
<% end %>

<% if !params[:term] && !params[:tag] %>
  <%= paginate(@posts) %>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class ="title">
    <u><%= @post.title %></u>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    <% if user_signed_in? && current_user.id == @post.user_id %>
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
    <% end %>
    <% if user_signed_in? && current_user.id != @post.user_id %>
    | <a href="#comment_form" style="color: #4d94ff;">Comment</a>
    <% end %>
  </p>

  <p class="body" style="white-space: pre-line;">
    <%= @post.body %>
  </p>

  <div id="comments">
      <h2><%= pluralize(@post.comments.count, "Comment") %></h2>
      <%= render @post.comments %>

  <% if user_signed_in? %>
      <u><h3 id="comment_form">Comment Form</h3></u>
      <%= render "comments/form" %>
  </div>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if @comment.errors.any? %>
<div id="errors">
  <h2><%= pluralize(@comment.errors.count, "error") %> prevented your comment from saving</h2>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- <% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %> -->

app/views/users/posts.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <p class="date">
        Author: <%= post.user.name %><br>
        Date: <%= post.created_at.strftime("%B, %d, %Y") %><br>
        Tags: <%= raw post.tag_list.map { |t| link_to t.capitalize, tag_path(t),:style=>'color: #4d94ff;' }.join(", ") %>
      </p>
    </div>
<% end %>